version: "3.3"

services:
  my-server:
    build:
      context: ./python_flask_server
    restart: always
    environment:
      VIRTUAL_HOST: mader.xyz, v1.mader.xyz, v1.mader.lo
      LETSENCRYPT_HOST: mader.xyz, v1.mader.xyz
      LETSENCRYPT_EMAIL: vincent.mader@icloud.com
    ports:
      - 5001:5001
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
    name: proxy_mxyz_proxy_network 
    # ^ This has to be the same name as specified in `./proxy/docker-compose.yml`.
    #   Additionally, it it prefixed by the proxy directory name (see "docker network ls").
